dist: trusty
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
script:
   - npm install
   - npm run lint
   - npm test
branches:
  only:
    - master
notifications:
  irc: "irc.freenode.org#bucharest-gold"
